name: Stats

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 22 * * *"

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run logcli
        run: |      
          curl -sSLO https://github.com/grafana/loki/releases/download/v2.4.2/logcli-linux-amd64.zip
          unzip logcli-linux-amd64.zip
          chmod a+x logcli-linux-amd64
          ./logcli-linux-amd64 -q --org-id=${ORG_ID} instant-query 'topk(25, sum(count_over_time({path=~"/tool/.*"}[2d])) by (path))'
        env:
          ORG_ID: ${{secrets.LOKI_ORG_ID}}
          LOKI_ADDR: http://loki.jorgelbg.me
